// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TestVadarod.Repositories;

#nullable disable

namespace TestVadarod.Migrations
{
    [DbContext(typeof(CurrencyRateDbContext))]
    partial class CurrencyRateDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TestVadarod.Data.Models.Rate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Cur_Abbreviation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Cur_ID")
                        .HasColumnType("integer");

                    b.Property<string>("Cur_Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("Cur_OfficialRate")
                        .HasColumnType("numeric");

                    b.Property<int>("Cur_Scale")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Rates");
                });
#pragma warning restore 612, 618
        }
    }
}
